print("yokoso isekai")
print("hello dunia")
print("apa kabarmu?")
print("darimana asalmu?")
print("apakah kamu ingin berteman dengan saya?")
print("seprtinya cuaca sedang bagus ya?")
print("mari kita belajar tentang python")
print("apakah anda mengetahui tentang python?")
print("saya suka nonton anime")
print("pacar saya 2d")